[book]
authors = ["meng.yan"]
language = "zh-cn"
multilingual = false
src = "src"
title = "佛、道、儒"

[output.html]
additional-css = ["theme/custom.css"]  # 额外 CSS
mathjax-support = true

# 显示指定行内公式的分隔符
[output.html.mathjax]
inline = [['$', '$'], ['\\(', '\\)']]

[output.html.print]
enable = false

[output.html.search]
enable = false
